config/routes.rb
Rails.application.routes.draw do
  resources :companies do 
    collection { post :import }
  end
  resources :posts
  resources :post
  resources :users
  resources :user
  mount ActiveAnalytics::Engine, at: "analytics"
  get '/' => 'users#index'
  get '/posts' => 'posts#index'
  post 'sessions' => 'sessions#create'
  post '/users' => 'users#create'
  get '/dashboard' => 'crms#index'
  get '/admin' => 'admin#userpage'
  get 'logs' => 'logs#index'
  get 'companies' => 'companies#index'
  get 'logout'  => 'sessions#destroy'
  get '/crmusers' => 'users#usermanage'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/home' => 'home#index'
end

app/models/ahoy/event.rb
class Ahoy::Event < ApplicationRecord
  include Ahoy::QueryMethods

  self.table_name = "ahoy_events"

  belongs_to :visit
  belongs_to :user, optional: true

  serialize :properties, JSON
end

app/models/ahoy/visit.rb
class Ahoy::Visit < ApplicationRecord
  self.table_name = "ahoy_visits"

  has_many :events, class_name: "Ahoy::Event"
  belongs_to :user, optional: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ActiveRecord::Base
    validates_presence_of :name
    validates_presence_of :manager
    validates_presence_of :created_at
    validates_presence_of :updated_at

    def self.import(file)
     CSV.foreach(file.path, headers: true) do |row|
        Company.create! row.to_hash
     end
    end
end
 

app/models/post.rb
class Post < ApplicationRecord
    validates :title, presence: true
    validates_presence_of :title
    validates_presence_of :content
    mount_uploader :image, ImageUploader
    
    def to_s
      title
    end
  end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
    def userpage
        if !session[:user_id]
            flash[:login_errors] = 'User Not Logged-In. Please Log-In/Register'
            redirect_to '/'
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :record_page_view
    include SessionsHelper
  
    def record_page_view
      ActiveAnalytics.record_request(request)
    end
  end
  

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: %i[ show edit update destroy ]

  # GET /companies or /companies.json
  def index
    if !session[:user_id]
        flash[:login_errors] = 'User Not Logged-In. Please Log-In/Register'
        redirect_to '/'
    end
    @companies = Company.all
  end

  # GET /companies/1 or /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies or /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to company_url(@company), notice: "Company was successfully created." }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1 or /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to company_url(@company), notice: "Company was successfully updated." }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1 or /companies/1.json
  def destroy
    @company.destroy

    respond_to do |format|
      format.html { redirect_to companies_url, notice: "Company was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def import
    Company.import(params[:file])
    redirect_to companies_path, notice: "Companies Added Successfully"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def company_params
      params.require(:company).permit(:name, :manager, :status, :terms)
    end
end

app/controllers/crms_controller.rb
class CrmsController < ApplicationController
    def index
        if !session[:user_id]
            flash[:login_errors] = 'User Not Logged-In. Please Log-In/Register'
            redirect_to '/'
        end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
    def index
        if !session[:user_id]
            flash[:login_errors] = 'User Not Logged-In. Please Log-In/Register'
            redirect_to '/'
        end
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :set_post, only: %i[ show edit update destroy ]
  
    def index
      @posts = Post.all
      respond_to do |format|
        format.html
        format.pdf do
          render pdf: "Posts: #{@posts.count}", template: "posts/index.html.erb"
        end
      end
    end
  
    def show
      respond_to do |format|
        format.html
        format.pdf do
          render pdf: "Post id: #{@post.id}", template: "posts/show.html.erb"
        end
      end
    end
  
    def new
      @post = Post.new
    end
  
    def edit
    end
  
    def create
      @post = Post.new(post_params)
      if @post.save
        EventMailer.event_created.deliver_later
        redirect_to @post, notice: "Post was successfully created."
      else
        render :new, status: :unprocessable_entity
      end
    end
  
    def update
      if @post.update(post_params)
        redirect_to @post, notice: "Post was successfully updated."
      else
        render :edit, status: :unprocessable_entity
      end
    end
  
    def destroy
      @post.destroy
      redirect_to posts_url, notice: "Post was successfully destroyed."
    end
  
    private
      def set_post
        @post = Post.find(params[:id])
      end
  
      def post_params
        params.require(:post).permit(:title, :content, :image)
      end
  end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def create
        user = User.find_by(email:login_params[:email])
        if !user
            flash[:login_errors] = 'Incorrect email or password'
            redirect_to '/' 
        elsif user && user.authenticate(login_params[:password])
            session[:user_id] = user.id
            redirect_to '/dashboard'
        else 
            flash[:login_errors] = 'Incorrect email or password'
            redirect_to '/'
        end
    end

    def destroy
        log_out if logged_in?
        flash[:login_errors] = 'Logged Out Successfully. Log In again to view.'
        redirect_to '/'
    end

    private
        def login_params
            params.require(:login).permit(:email,:password)
        end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
      @users = User.all
  end

  def create
      user = User.find_by(email:user_params[:email])
      if user
        flash[:login_errors] = 'User already exists. Please Login.'
        redirect_to '/'
      else
        user = User.new(user_params)
        if user.save
          session[:user_id] = user.id
          redirect_to '/dashboard'
        else 
          flash[:danger] = 'Invalid email/password combination' # Not quite right!
          render 'new'
          # flash[:register_errors] = user.errors.full_messages
          # redirect_to '/'
        end
      end
  end

  private 
      def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
      end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/crms_helper.rb
module CrmsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end
    def logged_in?
        !current_user.nil?
    end
    def log_out
        session.delete(:user_id)
        @current_user = nil
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/companies/_form.html.erb
<%= form_with(model: company) do |form| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
        <% company.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :manager %>
    <%= form.text_field :manager %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="field">
    <%= form.label :terms %>
    <%= form.number_field :terms %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>
<h1 class="pg-title"><u>Upload Reports</u></h1>
<div class="tbl-wrapper">
  <table class="crm-tbl">
    <thead>
      <tr>
        <th>Name</th>
        <th>Manager</th>
        <th>Status</th>
        <th>Terms</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @companies.each do |company| %>
        <tr>
          <td><%= company.name %></td>
          <td><%= company.manager %></td>
          <td><%= company.status %></td>
          <td><%= company.terms %></td>
          <td><%= link_to 'Show', company %></td>
          <td><%= link_to 'Edit', edit_company_path(company) %></td>
          <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>
<div class="tbl-wrapper">
  <h3>Import Reports</h3>
  <%= form_tag import_companies_path, multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag "Upload Reports", class: "tbl-submit"%>
  <% end %>
  <%= link_to 'New Report', new_company_path %>
</div>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<p>
  <strong>Manager:</strong>
  <%= @company.manager %>
</p>

<p>
  <strong>Status:</strong>
  <%= @company.status %>
</p>

<p>
  <strong>Terms:</strong>
  <%= @company.terms %>
</p>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>

app/views/crms/index.html.erb
<h1 class="pg-title"><u>Admin Dashboard</u></h1>
<br>
<div>
  <%= link_to "User Management", admin_url, class: "crm-btn" %>
</div>
<div>
  <%= link_to "Views Analytics", "/analytics", class: "crm-btn" %>
</div>
<div>
  <%= link_to "Logs", logs_url, class: "crm-btn" %>
</div>
<div>
  <%= link_to "Upload Reports", companies_url, class: "crm-btn" %>
</div>
<div>
  <%= link_to "Send Emails", posts_url, class: "crm-btn" %>
</div>
<div>
  <%= link_to "CRM users", "/crmusers", class: "crm-btn" %>
</div>

app/views/home/index.html.erb
<h2>Hello SE</h2>
<p>
  The time is now: <%= Time.now %>
</p>

app/views/logs/index.html.erb
<p>
  01 
  03/22 08:51:01 INFO   :.main: *************** RSVP Agent started ***************
  <br/>
  02 
  03/22 08:51:01 INFO   :...locate_configFile: Specified configuration file: /u/user10/rsvpd1.conf
  03/22 08:51:01 INFO   :.main: Using log level 511
  03/22 08:51:01 INFO   :..settcpimage: Get TCP images rc - EDC8112I Operation not supported on socket.
  <br/>
  03 
  03/22 08:51:01 INFO   :..settcpimage: Associate with TCP/IP image name = TCPCS
  03/22 08:51:02 INFO   :..reg_process: registering process with the system
  03/22 08:51:02 INFO   :..reg_process: attempt OS/390 registration
  03/22 08:51:02 INFO   :..reg_process: return from registration rc=0
  <br/>
  04 
  03/22 08:51:06 TRACE  :...read_physical_netif: Home list entries returned = 7
  03/22 08:51:06 INFO   :...read_physical_netif: index #0, interface VLINK1 has address 129.1.1.1, ifidx 0
  03/22 08:51:06 INFO   :...read_physical_netif: index #1, interface TR1 has address 9.37.65.139, ifidx 1
  03/22 08:51:06 INFO   :...read_physical_netif: index #2, interface LINK11 has address 9.67.100.1, ifidx 2
  03/22 08:51:06 INFO   :...read_physical_netif: index #3, interface LINK12 has address 9.67.101.1, ifidx 3
  03/22 08:51:06 INFO   :...read_physical_netif: index #4, interface CTCD0 has address 9.67.116.98, ifidx 4
  03/22 08:51:06 INFO   :...read_physical_netif: index #5, interface CTCD2 has address 9.67.117.98, ifidx 5
  03/22 08:51:06 INFO   :...read_physical_netif: index #6, interface LOOPBACK has address 127.0.0.1, ifidx 0
  03/22 08:51:06 INFO   :....mailslot_create: creating mailslot for timer
  03/22 08:51:06 INFO   :...mailbox_register: mailbox allocated for timer
  <br/>
  05 
  03/22 08:51:06 INFO   :.....mailslot_create: creating mailslot for RSVP
  03/22 08:51:06 INFO   :....mailbox_register: mailbox allocated for rsvp
  03/22 08:51:06 INFO   :.....mailslot_create: creating mailslot for RSVP via UDP
  <br/>
  06 
  03/22 08:51:06 WARNING:.....mailslot_create: setsockopt(MCAST_ADD) failed - EDC8116I Address not available.
  03/22 08:51:06 INFO   :....mailbox_register: mailbox allocated for rsvp-udp
  03/22 08:51:06 TRACE  :..entity_initialize: interface 129.1.1.1, entity for rsvp allocated and initialized
  03/22 08:51:06 INFO   :.....mailslot_create: creating mailslot for RSVP
  03/22 08:51:06 INFO   :....mailbox_register: mailbox allocated for rsvp
  03/22 08:51:06 INFO   :.....mailslot_create: creating mailslot for RSVP via UDP
  03/22 08:51:06 WARNING:.....mailslot_create: setsockopt(MCAST_ADD) failed - EDC8116I Address not available.
  03/22 08:51:06 INFO   :....mailbox_register: mailbox allocated for rsvp-udp
  03/22 08:51:06 TRACE  :..entity_initialize: interface 9.37.65.139, entity for rsvp allocated and 
  initialized
  <br/>
  03/22 08:51:06 INFO   :.....mailslot_create: creating mailslot for RSVP
  03/22 08:51:06 INFO   :....mailbox_register: mailbox allocated for rsvp
  03/22 08:51:06 INFO   :.....mailslot_create: creating mailslot for RSVP via UDP
  03/22 08:51:06 WARNING:.....mailslot_create: setsockopt(MCAST_ADD) failed - EDC8116I Address not available.
  03/22 08:51:06 INFO   :....mailbox_register: mailbox allocated for rsvp-udp
  03/22 08:51:06 TRACE  :..entity_initialize: interface 9.67.100.1, entity for rsvp allocated and initialized
  03/22 08:51:06 INFO   :.....mailslot_create: creating mailslot for RSVP
  03/22 08:51:06 INFO   :....mailbox_register: mailbox allocated for rsvp
  03/22 08:51:06 INFO   :.....mailslot_create: creating mailslot for RSVP via UDP
  03/22 08:51:06 WARNING:.....mailslot_create: setsockopt(MCAST_ADD) failed - EDC8116I Address not available.
  03/22 08:51:06 INFO   :....mailbox_register: mailbox allocated for rsvp-udp
  03/22 08:51:06 TRACE  :..entity_initialize: interface 9.67.101.1, entity for rsvp allocated and initialized
  03/22 08:51:06 INFO   :.....mailslot_create: creating mailslot for RSVP
  03/22 08:51:06 INFO   :....mailbox_register: mailbox allocated for rsvp
  03/22 08:51:06 INFO   :.....mailslot_create: creating mailslot for RSVP via UDP
  03/22 08:51:06 INFO   :....mailbox_register: mailbox allocated for rsvp-udp
  03/22 08:51:06 TRACE  :..entity_initialize: interface 9.67.116.98, entity for rsvp allocated and 
  initialized
  <br/>
  03/22 08:51:06 INFO   :.....mailslot_create: creating mailslot for RSVP
  03/22 08:51:06 INFO   :....mailbox_register: mailbox allocated for rsvp
  03/22 08:51:06 INFO   :.....mailslot_create: creating mailslot for RSVP via UDP
  03/22 08:51:06 INFO   :....mailbox_register: mailbox allocated for rsvp-udp
  03/22 08:51:06 TRACE  :..entity_initialize: interface 9.67.117.98, entity for rsvp allocated and 
  initialized
  <br/>
</p>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, required: true %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1 class="pg-title"><u>Email Notifications</u></h1>
<div class="tbl-wrapper">
  <table class="crm-tbl">
    <thead>
      <tr>
        <th>Id</th>
        <th>Title</th>
        <th>Content</th>
        <th colspan="4"></th>
      </tr>
    </thead>
    <tbody>
      <% @posts.each do |post| %>
        <tr>
          <td><%= post.id %></td>
          <td><%= post.title %></td>
          <td><%= simple_format(post.content) %></td>
          <td><%= link_to 'PDF', post_path(post, format: :pdf) %></td>
          <td><%= link_to 'Show', post %></td>
          <td><%= link_to 'Edit', edit_post_path(post) %></td>
          <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br/>
<div class="tbl-wrapper">
  <h3>Import Reports</h3>
  <%= link_to 'New Report', new_post_path %>
  <br/>
  <%= link_to "Reports PDF", posts_path(format: :pdf) %>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/post.html.erb
PDF generation date:
<%= Time.zone.now %>

<p>
  <strong>Post ID:</strong>
  <%= @post.id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= simple_format(@post.content) %>
</p>

app/views/posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= simple_format(@post.content) %>
</p>

<%= image_tag(@post.image.url, alt: 'Attachment') if @post.image? %>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/users/index.html.erb
<% content_for :head do %>
  <!-- Font Awesome -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet" />
  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />
  <!-- MDB -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.0.0/mdb.min.css" rel="stylesheet" />
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.0.0/mdb.min.js"></script>
<% end %>
<div id="vanta-mainbody">
  <div class="login-wrapper">
    <h2 class="login-title"> CRM-SERVICE </h2>
    <% flash.each do |message_type, message| %>
      <div id="login-alert" class="alert alert-<%= message_type %>"><b><i><%= message %></i></b></div>
    <% end %>
    <hr/>
    <ul class="nav nav-pills nav-justified mb-3" id="ex1" role="tablist">
      <li class="nav-item" role="presentation">
        <a class="nav-link active" id="tab-login" data-mdb-toggle="pill" href="#pills-login" role="tab"
                aria-controls="pills-login" aria-selected="true">Login</a>
      </li>
      <li class="nav-item" role="presentation">
        <a class="nav-link" id="tab-register" data-mdb-toggle="pill" href="#pills-register" role="tab"
                aria-controls="pills-register" aria-selected="false">Register</a>
      </li>
    </ul>
    <div class="tab-content">
      <div class="tab-pane fade show active" id="pills-login" role="tabpanel" aria-labelledby="tab-login">
        <form action="/sessions" method="POST">
          <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
          <!-- Email input -->
          <div class="form-outline mb-4">
            <input type="email" name = "login[email]" id="registerEmail" class="form-control" />
            <label class="form-label" for="registerEmail">Email</label>
          </div>
          <!-- Password input -->
          <div class="form-outline mb-4">
            <input type="password" name="login[password]" id="loginPassword" class="form-control" />
            <label class="form-label" for="login[password]">Password</label>
          </div>
          <!-- 2 column grid layout -->
          <div class="row mb-4">
            <div class="col-md-6 d-flex justify-content-center">
            </div>
          </div>
          <!-- Submit button -->
          <%# <input type="submit" name="submit" class="submit"> %>
          <button type="submit" name="submit" class="btn btn-primary btn-block mb-3">Sign in</button>
        </form>
      </div>
      <div class="tab-pane fade" id="pills-register" role="tabpanel" aria-labelledby="tab-register">
        <form action="/users" method="POST">
          <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
          <!-- Name input -->
          <div class="form-outline mb-4">
            <input type="name" name="user[name]" id="registerName" class="form-control" />
            <label class="form-label" for="registerName">Name</label>
          </div>
          <!-- Email input -->
          <div class="form-outline mb-4">
            <input type="email" name="user[email]" id="registerEmail" class="form-control" />
            <label class="form-label" for="registerEmail">Email</label>
          </div>
          <!-- Password input -->
          <div class="form-outline mb-4">
            <input type="password" name="user[password]" id="registerPassword" class="form-control" />
            <label class="form-label" for="registerPassword">Password</label>
          </div>
          <!-- Repeat Password input -->
          <div class="form-outline mb-4">
            <input type="password" name="user[password_confirmation]" id="registerRe-enterPassword" class="form-control" />
            <label class="form-label" for="registerRe-enterPassword">Re-enter password</label>
          </div>
          <!-- Submit button -->
          <button type="submit" name="submit" class="btn btn-primary btn-block mb-3">Register</button>
        </form>
      </div>
    </div>
  </div>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r134/three.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/vanta@latest/dist/vanta.net.min.js"></script>
<script>
  VANTA.NET({
    el: "#vanta-mainbody",
    mouseControls: true,
    touchControls: true,
    gyroControls: false,
    minHeight: 200.00,
    minWidth: 200.00,
    scale: 1.00,
    scaleMobile: 1.00,
    color: 0x3fffe8,
    backgroundColor: 0x1e153c,
    maxDistance: 30.00,
    spacing: 18.00
  })
</script>

app/views/users/usermanage.html.erb
<h1 class="pg-title"><u>CRM USERS</u></h1>
<div class="tbl-wrapper">
  <table class="crm-tbl">
    <thead>
      <tr class="filters">
        <th>Id</th>
        <th>User</th>
        <th>Email</th>
        <th>Created At</th>
        <th>Updated At</th>
      </tr>
    </thead>
    <tbody>
      <% User.all.each do |user| %>
        <tr>
          <td><%= user.id %></td>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td><%= user.created_at %></td>
          <td><%= user.updated_at %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>