config/routes.rb
Rails.application.routes.draw do
  resources :companies do 
    collection { post :import }
  end
  resources :posts
  resources :post
  resources :users
  resources :user
  mount ActiveAnalytics::Engine, at: "analytics"
  get '/' => 'users#index'
  get '/posts' => 'posts#index'
  post 'sessions' => 'sessions#create'
  post '/users' => 'users#create'
  get '/dashboard' => 'crms#index'
  get '/admin' => 'admin#userpage'
  get 'logs' => 'logs#index'
  get 'companies' => 'companies#index'
  get 'logout'  => 'sessions#destroy'
  get '/crmusers' => 'users#usermanage'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/home' => 'home#index'
end

app/models/ahoy/event.rb
class Ahoy::Event < ApplicationRecord
  include Ahoy::QueryMethods

  self.table_name = "ahoy_events"

  belongs_to :visit
  belongs_to :user, optional: true

  serialize :properties, JSON
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ActiveRecord::Base
    validates_presence_of :name
    validates_presence_of :manager
    validates_presence_of :created_at
    validates_presence_of :updated_at

    def self.import(file)
     CSV.foreach(file.path, headers: true) do |row|
        Company.create! row.to_hash
     end
    end
end
 

app/models/post.rb
class Post < ApplicationRecord
    validates :title, presence: true
    validates_presence_of :title
    validates_presence_of :content
    mount_uploader :image, ImageUploader
    
    def to_s
      title
    end
  end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
    def userpage
        if !session[:user_id]
            flash[:login_errors] = 'User Not Logged-In. Please Log-In/Register'
            redirect_to '/'
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :record_page_view
    include SessionsHelper
  
    def record_page_view
      ActiveAnalytics.record_request(request)
    end
  end
  

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: %i[ show edit update destroy ]

  # GET /companies or /companies.json
  def index
    if !session[:user_id]
        flash[:login_errors] = 'User Not Logged-In. Please Log-In/Register'
        redirect_to '/'
    end
    @companies = Company.all
  end

  # GET /companies/1 or /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies or /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to company_url(@company), notice: "Company was successfully created." }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1 or /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to company_url(@company), notice: "Company was successfully updated." }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1 or /companies/1.json
  def destroy
    @company.destroy

    respond_to do |format|
      format.html { redirect_to companies_url, notice: "Company was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def import
    Company.import(params[:file])
    redirect_to companies_path, notice: "Companies Added Successfully"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def company_params
      params.require(:company).permit(:name, :manager, :status, :terms)
    end
end

app/controllers/crms_controller.rb
class CrmsController < ApplicationController
    def index
        if !session[:user_id]
            flash[:login_errors] = 'User Not Logged-In. Please Log-In/Register'
            redirect_to '/'
        end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
    def index
        if !session[:user_id]
            flash[:login_errors] = 'User Not Logged-In. Please Log-In/Register'
            redirect_to '/'
        end
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :set_post, only: %i[ show edit update destroy ]
  
    def index
      @posts = Post.all
      respond_to do |format|
        format.html
        format.pdf do
          render pdf: "Posts: #{@posts.count}", template: "posts/index.html.erb"
        end
      end
    end
  
    def show
      respond_to do |format|
        format.html
        format.pdf do
          render pdf: "Post id: #{@post.id}", template: "posts/show.html.erb"
        end
      end
    end
  
    def new
      @post = Post.new
    end
  
    def edit
    end
  
    def create
      @post = Post.new(post_params)
      if @post.save
        EventMailer.event_created.deliver_later
        redirect_to @post, notice: "Post was successfully created."
      else
        render :new, status: :unprocessable_entity
      end
    end
  
    def update
      if @post.update(post_params)
        redirect_to @post, notice: "Post was successfully updated."
      else
        render :edit, status: :unprocessable_entity
      end
    end
  
    def destroy
      @post.destroy
      redirect_to posts_url, notice: "Post was successfully destroyed."
    end
  
    private
      def set_post
        @post = Post.find(params[:id])
      end
  
      def post_params
        params.require(:post).permit(:title, :content, :image)
      end
  end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def create
        user = User.find_by(email:login_params[:email])
        if !user
            flash[:login_errors] = 'Incorrect email or password'
            redirect_to '/' 
        elsif user && user.authenticate(login_params[:password])
            session[:user_id] = user.id
            redirect_to '/dashboard'
        else 
            flash[:login_errors] = 'Incorrect email or password'
            redirect_to '/'
        end
    end

    def destroy
        log_out if logged_in?
        flash[:login_errors] = 'Logged Out Successfully. Log In again to view.'
        redirect_to '/'
    end

    private
        def login_params
            params.require(:login).permit(:email,:password)
        end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
      @users = User.all
  end

  def create
      user = User.find_by(email:user_params[:email])
      if user
        flash[:login_errors] = 'User already exists. Please Login.'
        redirect_to '/'
      else
        user = User.new(user_params)
        if user.save
          session[:user_id] = user.id
          redirect_to '/dashboard'
        else 
          flash[:danger] = 'Invalid email/password combination' # Not quite right!
          render 'new'
          # flash[:register_errors] = user.errors.full_messages
          # redirect_to '/'
        end
      end
  end

  private 
      def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
      end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/crms_helper.rb
module CrmsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end
    def logged_in?
        !current_user.nil?
    end
    def log_out
        session.delete(:user_id)
        @current_user = nil
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/userpage.html.erb
<h1 class="pg-title"><u>User Management</u></h1>
<script>
  var __basePath = './';
</script>
<script src="https://www.ag-grid.com/archive/25.0.0/dev/@ag-grid-community/all-modules/dist/ag-grid-community.js"></script>
<div>
  <%= link_to "E-mail", "/rails/mailers/event_mailer/event_created.html", class: "crm-btn" %>
  <select id="test" onchange="sendRequest(this.value)">
    <option value="">--Choose--</option>
    <option value=<%=Rails.configuration.urls['castnxt_url']%>>CastNXT</option>
    <option value=<%=Rails.configuration.urls['eventnxt_url']%>>EventNXT</option>
  </select>
</div>
<div id="myGrid" class="ag-theme-alpine"></div>

<script>
    var filterParams = {
        comparator: function (filterLocalDateAtMidnight, cellValue) {
        var dateAsString = cellValue;
        if (dateAsString == null) return -1;
        var dateParts = dateAsString.split('/');
        var cellDate = new Date(
        Number(dateParts[2]),
        Number(dateParts[1]) - 1,
        Number(dateParts[0])
        );

        if (filterLocalDateAtMidnight.getTime() === cellDate.getTime()) {
        return 0;
        }

        if (cellDate < filterLocalDateAtMidnight) {
        return -1;
        }

        if (cellDate > filterLocalDateAtMidnight) {
        return 1;
        }
        },
    browserDatePicker: true,
        };

    //---------For mock data-------------------
    // var columnDefs = [
    // { field: 'Customer Name'},
    // { field: 'Contact'},
    // { field: 'Country'},
    // { field: 'Logged In App'},
    // { field: 'Active Time(mins)',filter: 'agNumberColumnFilter'},
    // {
    //     field: 'Last Logged In',
    //     filter: 'agDateColumnFilter',
    // },
    // ];

    var columnDefs = [
    { field: 'name'},
    { field: 'email'},
    {
        headerName: "Location",
        field: 'talentData',
        cellStyle: {},
        cellRenderer: function(params){
            talentData = params.data.talentData
            if(talentData){
                talentData = JSON.parse(talentData)
                return talentData.city+", "+talentData.state
            } else {
                return "-"
            }
        }
    },
    {
        headerName: "Payment Link",
        field: 'Payment Link',
        cellStyle: {},
        cellRenderer: function(params){
            talentData = params.data.talentData
            if(talentData){
                talentData = JSON.parse(talentData)
                return talentData.paymentLink
            } else {
                return "-"
            }
        }
    },
    {
        headerName: "Active Status",
        field: 'is_active',
        cellStyle: {},
        cellRenderer: function(params){
            // return '<button>'+params.value+'</button>'
            if(params.value)
                return '<label class="switch"> <input type="checkbox" checked onclick="changeUserStatus(\''+ params.data._id["$oid"] +'\')" > <span class="slider round"></span> </label>'
            else
                return '<label class="switch"> <input type="checkbox" onclick="changeUserStatus(\''+ params.data._id["$oid"] +'\')" > <span class="slider round"></span> </label>'
        }
    },
    {
        field: 'updated_at',
        filter: 'agDateColumnFilter',
    },
    ];

    var gridOptions = {
        columnDefs: columnDefs,
        defaultColDef: {
            flex: 1,
            minWidth: 150,
            filter: true
        },
        //----------for setting mock data-------------
        // onGridReady: (e) => {renderTable(e.api)}
    };


        //----------------Implementation for mock data s----------------------
    // var gridDiv = document.querySelector('#myGrid');
    // new agGrid.Grid(gridDiv, gridOptions);

    // function renderTable(api){
    //     let data = [ { "Customer Name":"Alfreds Futterkiste", "Contact":"Maria Anders", "Country":"Germany", "Logged In App":"Event.NXT", "Last Logged In":"<%= Time.now %>", "Active Time(mins)":30 },
    //                 { "Customer Name":"Berglunds snabbköp", "Contact":"Christina Berglund", "Country":"Sweden", "Logged In App":"Fashion.NXT", "Last Logged In":"<%= Time.now %>", "Active Time(mins)":25 },
    //                 { "Customer Name":"Centro comercial Moctezuma", "Contact":"Francisco Chang", "Country":"Mexico", "Logged In App":"Cast.NXT", "Last Logged In":"<%= Time.now %>", "Active Time(mins)":25 },
    //                 { "Customer Name":"Ernst Handel", "Contact":"Roland Mendel", "Country":"Austria", "Logged In App":"Event.NXT", "Last Logged In":"<%= Time.now %>", "Active Time(mins)":25 },
    //                 { "Customer Name":"Island Trading", "Contact":"Helen Bennett", "Country":"UK", "Logged In App":"Cast.NXT", "Last Logged In":"<%= Time.now %>", "Active Time(mins)":25 },
    //                 { "Customer Name":"Königlich Essen", "Contact":"Philip Cramer", "Country":"Germany", "Logged In App":"Fashion.NXT", "Last Logged In":"<%= Time.now %>", "Active Time(mins)":25 } ]
    //     api.setRowData(data);
    // }

    //var apiUrl = "https://castnxt-final.herokuapp.com/api"

    //----------------Implement this once we get API's from other teams----------------------
    var gridDiv = document.querySelector('#myGrid');
    new agGrid.Grid(gridDiv, gridOptions);

    function sendRequest(url){
    //Clear the table
    gridOptions.api.setRowData([]);

    var requestOptions = {
        method: 'GET',
        redirect: 'follow'
    };

    fetch(url, requestOptions)
    .then(response => response.json())
      .then(result => {gridOptions.api.setRowData(result)})
      .catch(error => console.log('error', error));
      }
      const apiUrl = document.getElementById("test").value;
      document.addEventListener('DOMContentLoaded', sendRequest(apiurl));
      function changeUserStatus(id) {
      const url = document.getElementById("test").value;
      fetch(url + "/change_status/" + id)
      .then(response => response.json())
      // .then(result => console.log(result))
      .catch(error => console.log('error', error));
      }
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>FashioNXT</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= yield :head %>
  </head>
  <body>
    <% if !current_page?('/') %>
      <%= link_to "Home", dashboard_url, class: "crm-btn" %>
      <%= link_to "Log Out", logout_url, class: "crm-btn right"%>
    <% end %>
    <%= yield %>
  </body>
</html>